### PR TITLE
kubectl debug

### PR DESCRIPTION
**Pull request by guettli**
Use `kubectl debug` as first K8s example.

This is very powerful, since you can get into the pod.

### CODE REVIEW

**Comment by nickolaev** [comment]
I can see this related to the proposed k9s change here:
https://github.com/derailed/k9s/pull/1850

I mean configuring `netshoot` as the debug image in `k9` will be the ultimate application for the project.

**Comment by nicolaka** [comment]
thanks @guettli for the PR. Can you update the PR and leave the `If you want to spin up a throw away container for debugging.` note as is and add the debug command underneath it ? there are use-cases for both debug and throwaway pod.

**Comment by guettli** [comment]
@nicolaka I added the old example again, but changed the wording a bit. That's something which confused me some days ago. `kubectl run` creates a pod. `kubectl debug` runs a container in an existing pod.

**Comment by guettli** [comment]
@nicolaka Please have a second look at my PR. What needs to be done next?

**Pull request merged**
